apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-petclinic
  namespace: monitoring
  labels:
    app: spring-petclinic
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pet-clinic
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
  namespaceSelector:
    matchNames:
    - pet-clinic